// [command, description]
export const CHEATSHEET = {
  Git: [
    ['git init', 'Create a new repository'],
    ['git clone <url>', 'Clone a repository'],
    ['git status -sb', 'Short status with branch'],
    ['git add -p', 'Stage changes interactively'],
    ['git commit -m "msg"', 'Commit staged changes'],
    ['git commit --amend --no-edit', 'Add staged changes to the last commit'],
    ['git switch -c <branch>', 'Create and switch to a branch'],
    ['git branch -d <branch>', 'Delete a merged branch'],
    ['git fetch --prune', 'Fetch and remove stale remote branches'],
    ['git pull --rebase', 'Pull with rebase'],
    ['git push -u origin <branch>', 'Push and set upstream'],
    ['git log --oneline --graph --decorate', 'Compact history graph'],
    ['git diff --staged', 'Show staged changes'],
    ['git stash push -m "msg"', 'Stash working changes'],
    ['git stash pop', 'Apply and drop latest stash'],
    ['git reset --soft HEAD~1', 'Undo last commit, keep changes staged'],
    ['git reset --hard <commit>', 'Discard everything back to a commit'],
    ['git revert <commit>', 'Create a commit that undoes another'],
    ['git cherry-pick <commit>', 'Apply a commit onto the current branch'],
    ['git rebase -i HEAD~3', 'Interactively rewrite last 3 commits'],
    ['git reflog', 'Show history of HEAD movements'],
    ['git tag -a v1.0.0 -m "msg"', 'Create an annotated tag'],
  ],
  Docker: [
    ['docker ps -a', 'List all containers'],
    ['docker images', 'List images'],
    ['docker build -t name:tag .', 'Build an image'],
    ['docker run -d -p 8080:80 --name web nginx', 'Run a detached container with port mapping'],
    ['docker run --rm -it ubuntu bash', 'Interactive throwaway container'],
    ['docker exec -it <container> sh', 'Open a shell in a running container'],
    ['docker logs -f <container>', 'Follow container logs'],
    ['docker stop <container>', 'Stop a container'],
    ['docker rm -f <container>', 'Force remove a container'],
    ['docker rmi <image>', 'Remove an image'],
    ['docker volume ls', 'List volumes'],
    ['docker network ls', 'List networks'],
    ['docker compose up -d', 'Start compose services in background'],
    ['docker compose down -v', 'Stop services and remove volumes'],
    ['docker compose logs -f <service>', 'Follow a compose service log'],
    ['docker system prune -a', 'Remove unused images, containers, networks'],
    ['docker inspect <container>', 'Show low-level details'],
    ['docker cp <container>:/path ./local', 'Copy files out of a container'],
  ],
  Linux: [
    ['ls -lah', 'List files with sizes and hidden files'],
    ['cd -', 'Go to the previous directory'],
    ['grep -rn "text" .', 'Search recursively with line numbers'],
    ['find . -name "*.log" -mtime +7', 'Find log files older than 7 days'],
    ['tail -f file.log', 'Follow a file'],
    ['chmod 755 file', 'Set permissions rwxr-xr-x'],
    ['chown user:group file', 'Change owner'],
    ['ps aux | grep <name>', 'Find a process'],
    ['kill -9 <pid>', 'Force kill a process'],
    ['lsof -i :3000', 'Which process uses port 3000'],
    ['df -h', 'Disk usage by filesystem'],
    ['du -sh *', 'Size of each item in the directory'],
    ['top', 'Live process viewer'],
    ['curl -I <url>', 'Fetch response headers'],
    ['tar -czvf out.tar.gz dir/', 'Create a gzip tarball'],
    ['tar -xzvf file.tar.gz', 'Extract a gzip tarball'],
    ['ssh user@host', 'Connect over SSH'],
    ['scp file user@host:/path', 'Copy a file over SSH'],
    ['sed -i "s/old/new/g" file', 'Replace text in a file'],
    ['awk \'{print $1}\' file', 'Print the first column'],
    ['xargs -n1 <cmd>', 'Run a command for each input item'],
  ],
  'VS Code': [
    ['Cmd/Ctrl+Shift+P', 'Command palette'],
    ['Cmd/Ctrl+P', 'Quick open file'],
    ['Cmd/Ctrl+B', 'Toggle sidebar'],
    ['Cmd/Ctrl+`', 'Toggle terminal'],
    ['Cmd/Ctrl+D', 'Select next occurrence'],
    ['Cmd/Ctrl+Shift+L', 'Select all occurrences'],
    ['Alt+Up / Alt+Down', 'Move line up/down'],
    ['Shift+Alt+Up / Down', 'Copy line up/down'],
    ['Cmd/Ctrl+/', 'Toggle line comment'],
    ['Cmd/Ctrl+Shift+F', 'Search across files'],
    ['F12', 'Go to definition'],
    ['Shift+F12', 'Find references'],
    ['F2', 'Rename symbol'],
    ['Cmd/Ctrl+Shift+O', 'Go to symbol in file'],
    ['Cmd/Ctrl+K Cmd/Ctrl+S', 'Keyboard shortcuts'],
    ['Cmd/Ctrl+\\', 'Split editor'],
  ],
  npm: [
    ['npm init -y', 'Create package.json with defaults'],
    ['npm install', 'Install all dependencies'],
    ['npm install <pkg> -D', 'Install as dev dependency'],
    ['npm uninstall <pkg>', 'Remove a package'],
    ['npm run <script>', 'Run a package.json script'],
    ['npm ci', 'Clean install from lockfile'],
    ['npm outdated', 'List outdated packages'],
    ['npm update', 'Update to latest allowed versions'],
    ['npm ls --depth=0', 'List top-level packages'],
    ['npm audit fix', 'Fix known vulnerabilities'],
    ['npm cache clean --force', 'Clear the npm cache'],
    ['npx <pkg>', 'Run a package binary without installing'],
    ['npm version patch', 'Bump the patch version'],
    ['npm publish', 'Publish the package'],
  ],
  Kubernetes: [
    ['kubectl get pods -A', 'List pods in all namespaces'],
    ['kubectl describe pod <pod>', 'Pod details and events'],
    ['kubectl logs -f <pod>', 'Follow pod logs'],
    ['kubectl exec -it <pod> -- sh', 'Shell into a pod'],
    ['kubectl apply -f file.yaml', 'Apply a manifest'],
    ['kubectl rollout restart deploy/<name>', 'Restart a deployment'],
    ['kubectl port-forward svc/<name> 8080:80', 'Forward a local port'],
    ['kubectl config use-context <ctx>', 'Switch cluster context'],
  ],
};
