// Help content for every utility, keyed by the id used in config/utilities.js.
// Shape: { summary, howTo: string[], inputs, outputs, example?, tips?: string[] }
export const HELP = {
  calculator: {
    summary: 'A standard calculator for quick arithmetic.',
    howTo: ['Click the buttons or type with your keyboard.', 'Press Enter or = to get the result.', 'Use C to clear the display.'],
    inputs: 'Numbers and operators (buttons or keyboard).',
    outputs: 'The running calculation and result on the display.',
    example: '12 * (3 + 4) = 84',
    tips: ['Full keyboard support: digits, + - * /, Enter and Backspace all work.'],
  },
  calendar: {
    summary: 'Month calendar with UAE weekends, public holidays, week numbers and personal notes.',
    howTo: ['Use the arrows to move between months.', 'Click a day to add or edit a note for it.', 'Holidays and weekends are highlighted automatically.'],
    inputs: 'A month to view and optional notes per day.',
    outputs: 'A month grid with holidays, week numbers and your notes.',
    tips: ['Notes are stored in this app on your device only (browser local storage).'],
  },
  'useful-links': {
    summary: 'A personal bookmark list for the URLs you use often.',
    howTo: ['Enter a title and URL, then add the link.', 'Click a link to open it.', 'Delete links you no longer need.'],
    inputs: 'A title and a URL.',
    outputs: 'A saved, clickable list of links.',
    tips: ['Links are saved locally and are not synced between devices.'],
  },
  'date-diff-calculator': {
    summary: 'Find the difference between two dates in years, months, weeks, days, hours and more.',
    howTo: ['Pick a start date and an end date.', 'The difference is shown in every unit.'],
    inputs: 'Two dates.',
    outputs: 'The gap between them in each unit.',
    example: '2024-01-01 to 2024-12-25',
  },
  'timezone-converter': {
    summary: 'Convert one date and time across many timezones at once.',
    howTo: ['Choose the source date, time and timezone.', 'Add the timezones you want to compare.', 'Read the converted times in the results list.'],
    inputs: 'A date/time and a source timezone.',
    outputs: 'The same moment in each selected timezone.',
  },
  'markdown-editor': {
    summary: 'Write Markdown on the left and see the rendered result live on the right.',
    howTo: ['Type or paste Markdown in the editor.', 'The preview updates as you type.', 'Use the download button to save your work.'],
    inputs: 'Markdown text.',
    outputs: 'Rendered HTML preview and a downloadable file.',
    example: '# Title\n\n- item one\n- item two\n\n**bold** and `code`',
  },
  'currency-converter': {
    summary: 'Convert between 25+ currencies using live exchange rates.',
    howTo: ['Enter an amount.', 'Choose the "from" and "to" currencies.', 'The converted value appears below.'],
    inputs: 'An amount and two currencies.',
    outputs: 'The converted amount and the rate used.',
    tips: ['Desktop app only: rates are fetched by the app. The last result is cached so it works offline.'],
  },
  'world-clock': {
    summary: 'Live local time in major cities, shown on a day/night world map.',
    howTo: ['Look at the map to see which regions are in daylight.', 'Click a city card to select it and focus on its time.'],
    inputs: 'A city selection (click).',
    outputs: 'Current time and date for each city.',
  },
  'regex-tester': {
    summary: 'Try out regular expressions against sample text with matches highlighted.',
    howTo: ['Type your pattern (without the surrounding slashes).', 'Tick the flags you need (g, i, m, s, u).', 'Paste your test text; matches and capture groups appear immediately.'],
    inputs: 'A pattern, flags and test text.',
    outputs: 'Highlighted matches and a list of capture groups.',
    example: 'Pattern: (\\d{4})-(\\d{2})-(\\d{2})   Text: Released 2024-05-17',
    tips: ['An invalid pattern shows an error instead of results.'],
  },
  'string-tools': {
    summary: 'Change case, trim, reverse and count characters, words and lines.',
    howTo: ['Paste or type your text.', 'Click an operation (e.g. UPPERCASE, camelCase, reverse).', 'Copy the result.'],
    inputs: 'Any text.',
    outputs: 'Transformed text and text statistics.',
  },
  'uuid-generator': {
    summary: 'Generate random version 4 (RFC 4122) UUIDs in bulk.',
    howTo: ['Choose how many UUIDs you need.', 'Click Generate.', 'Copy one or all of them.'],
    inputs: 'A count.',
    outputs: 'A list of UUIDs.',
    example: '3f2b8c1e-5a7d-4e90-9b1a-2c4d6e8f0a12',
  },
  'json-viewer': {
    summary: 'Explore JSON as a collapsible, colour-coded tree.',
    howTo: ['Paste JSON into the input.', 'Click nodes to expand or collapse them.', 'Use Expand all / Collapse all, or Pretty-print to reformat the input.'],
    inputs: 'JSON text.',
    outputs: 'An interactive tree with typed values.',
    example: '{"name":"Ada","tags":["math","code"],"active":true}',
    tips: ['Invalid JSON shows a parse error so you can find the problem.'],
  },
  'cron-parser': {
    summary: 'Turn a cron expression into plain English and see when it will run next.',
    howTo: ['Type a cron expression (minute hour day-of-month month day-of-week).', 'Read the description and the list of upcoming run times.'],
    inputs: 'A 5-field cron expression.',
    outputs: 'A human-readable description and upcoming run times.',
    example: '*/15 9-17 * * 1-5   (every 15 minutes, 9–5, Monday to Friday)',
  },
  'yaml-comparator': {
    summary: 'Compare two YAML or .env style configs and see what differs.',
    howTo: ['Paste the first config on the left and the second on the right.', 'Review added, removed and changed keys.', 'Turn on "only differences" to hide identical lines.'],
    inputs: 'Two YAML (or env) texts.',
    outputs: 'A side-by-side diff.',
  },
  'yaml-sorter': {
    summary: 'Sort the keys of a YAML document alphabetically.',
    howTo: ['Paste your YAML.', 'The sorted output is shown.', 'Copy the result.'],
    inputs: 'YAML text.',
    outputs: 'YAML with keys sorted.',
    example: 'zebra: 1\napple: 2',
  },
  'code-formatter': {
    summary: 'Pretty-print JSON, XML, HTML, CSS or SQL.',
    howTo: ['Choose the language.', 'Paste your code.', 'Copy the formatted output.'],
    inputs: 'Code and a language.',
    outputs: 'Formatted code.',
    tips: ['Pick the right language first, otherwise the formatter may not recognise the syntax.'],
  },
  'curl-decoder': {
    summary: 'Break a curl command into its method, URL, headers and body.',
    howTo: ['Paste a curl command (e.g. copied from browser dev tools).', 'Read the decoded parts.'],
    inputs: 'A curl command.',
    outputs: 'Method, URL, headers and body.',
    example: "curl -X POST https://api.example.com/users -H 'Content-Type: application/json' -d '{\"name\":\"Ada\"}'",
  },
  'curl-builder': {
    summary: 'Build a curl command from a simple form.',
    howTo: ['Pick the method and enter the URL.', 'Add headers and a body if needed.', 'Copy the generated command.'],
    inputs: 'Method, URL, headers and body.',
    outputs: 'A ready-to-run curl command.',
  },
  'csv-viewer': {
    summary: 'View CSV data as a sortable, searchable table.',
    howTo: ['Paste CSV text or load a CSV file.', 'Click a column header to sort.', 'Use the filter box to narrow rows.'],
    inputs: 'CSV text or a file.',
    outputs: 'An interactive table.',
    example: 'name,age\nAda,36\nLinus,54',
  },
  'unix-timestamp': {
    summary: 'Convert between Unix epoch time and human-readable dates.',
    howTo: ['Enter an epoch value to see the date, or pick a date to get the epoch.', 'Copy the value you need.'],
    inputs: 'An epoch (seconds or milliseconds) or a date.',
    outputs: 'The matching date or epoch.',
    example: '1700000000 → 14 Nov 2023, 22:13:20 UTC',
  },
  'cidr-calculator': {
    summary: 'Work out network details for an IPv4 CIDR block.',
    howTo: ['Enter an address with prefix length, e.g. 192.168.1.0/24.', 'Read the network, mask, range and host count.'],
    inputs: 'An IPv4 CIDR.',
    outputs: 'Network address, subnet mask, usable range and number of hosts.',
    example: '10.0.0.0/22',
  },
  'color-converter': {
    summary: 'Convert colours between HEX, RGB, HSL and HSV and check WCAG contrast.',
    howTo: ['Enter a colour in any supported format.', 'See the other formats and the contrast ratio against black and white.'],
    inputs: 'A colour value.',
    outputs: 'Equivalent values in each format and contrast results.',
    example: '#af0e20  or  rgb(175, 14, 32)',
  },
  'number-system-converter': {
    summary: 'Convert numbers between binary, octal, decimal, hexadecimal and custom bases.',
    howTo: ['Enter a number and choose its base.', 'Read the value in every other base.', 'Copy the one you need.'],
    inputs: 'A number and its base.',
    outputs: 'The number in other bases.',
    example: '255 (decimal) = FF (hex) = 11111111 (binary)',
  },
  'dns-lookup': {
    summary: 'Resolve DNS records for a hostname.',
    howTo: ['Enter a hostname.', 'Select the record types (A, AAAA, MX, TXT…).', 'Run the lookup and read the records.'],
    inputs: 'A hostname and record types.',
    outputs: 'The DNS records returned.',
    tips: ['Desktop app only: lookups are performed by the app, not the browser.'],
  },
  'cert-inspector': {
    summary: 'Inspect the TLS certificate presented by any host and port.',
    howTo: ['Enter host:port, e.g. example.com:443.', 'Run the inspection.', 'Review the issuer, validity dates and fingerprints.'],
    inputs: 'host:port.',
    outputs: 'Certificate details.',
    tips: ['Desktop app only.'],
  },
  'http-tester': {
    summary: 'Send HTTP requests and view the response, without browser CORS limits.',
    howTo: ['Choose the method and enter the URL.', 'Add headers and a body if needed.', 'Send and inspect status, headers and body.'],
    inputs: 'Method, URL, headers, body.',
    outputs: 'The HTTP response.',
    tips: ['Desktop app only: requests are made by the app, so CORS does not apply.'],
  },
  'http-mock-server': {
    summary: 'Run a local mock HTTP server with stubbed routes and a live request log.',
    howTo: ['Choose a port and define stub routes (path, status, response).', 'Start the server.', 'Call it from your app or curl and watch requests appear in the log.', 'Stop the server when finished.'],
    inputs: 'A port and route definitions.',
    outputs: 'A running local server and a live request log.',
    tips: ['Desktop app only. Stop the server when done to free the port.'],
  },
  'fake-data-generator': {
    summary: 'Generate realistic test data offline as JSON or CSV.',
    howTo: ['Define the fields (schema) you need.', 'Set the number of rows.', 'Generate, then copy or download the data.'],
    inputs: 'A schema and a count.',
    outputs: 'JSON or CSV data.',
  },
  base64: {
    summary: 'Encode text to Base64 or decode Base64 back to text.',
    howTo: ['Choose Encode or Decode.', 'Enter your text.', 'Copy the result, or use swap to feed it back as input.'],
    inputs: 'Text or Base64.',
    outputs: 'The converted text.',
    example: 'Hello → SGVsbG8=',
  },
  'hash-generator': {
    summary: 'Generate MD5, SHA-1, SHA-256 and SHA-512 hashes of text.',
    howTo: ['Type or paste text.', 'All hashes are calculated at once.', 'Copy any hash; toggle uppercase if needed.'],
    inputs: 'Text.',
    outputs: 'Four hash values.',
    tips: ['MD5 and SHA-1 are not secure for passwords or signatures.'],
  },
  'jwt-decoder': {
    summary: 'Decode a JSON Web Token and check its expiry.',
    howTo: ['Paste a token (a leading "Bearer " is fine).', 'Read the header and payload.', 'Check the exp / nbf / iat badges for validity.'],
    inputs: 'A JWT.',
    outputs: 'Decoded header and payload with time-claim status.',
    tips: ['Decoding is local, but the signature is not verified.'],
  },
  'card-validator': {
    summary: 'Check card numbers (Luhn) and IBANs (MOD-97) offline.',
    howTo: ['Enter a card number or IBAN.', 'See whether it is valid.'],
    inputs: 'A card number or IBAN.',
    outputs: 'Valid / invalid result.',
    tips: ['This only checks the format and checksum. It does not confirm the account exists.'],
  },
  cheatsheet: {
    summary: 'A searchable command reference for Git, Docker, Linux and more.',
    howTo: ['Type in the search box to filter commands.', 'Click copy on a row to copy the command.'],
    inputs: 'A search term.',
    outputs: 'Matching commands with descriptions.',
    example: 'Search: stash',
  },
  'image-tools': {
    summary: 'Convert and compress images, and export images to PDF.',
    howTo: ['Add one or more images.', 'Choose the output format and quality.', 'Convert, then download each file (or the PDF).'],
    inputs: 'Image files, format and quality.',
    outputs: 'Converted/compressed images or a PDF.',
    tips: ['Everything is processed locally; images never leave your device.'],
  },
  'qr-code-generator': {
    summary: 'Create QR codes for URLs, text or Wi-Fi networks.',
    howTo: ['Choose the type (URL, text or Wi-Fi).', 'Fill in the details.', 'Download the QR image.'],
    inputs: 'A URL, text or Wi-Fi details.',
    outputs: 'A QR code image.',
  },
  'text-diff': {
    summary: 'Compare two texts line by line and see exactly what was added or removed.',
    howTo: ['Paste the original text on the left and the changed text on the right.', 'Green lines were added; red lines were removed.', 'Use the options to ignore case or whitespace, or show only the differences.', 'Swap swaps the two sides.'],
    inputs: 'Two blocks of text.',
    outputs: 'A line-numbered diff with counts of added, removed and unchanged lines.',
    tips: ['Good for comparing config files, logs or copy edits. For YAML-aware comparison use YAML Comparator.'],
  },
  'url-tools': {
    summary: 'Percent-encode text for use in URLs, decode it back, or split a URL into its parts.',
    howTo: ['Choose Encode, Decode or Parse URL.', 'Paste your text or URL.', 'Copy the output, or read the parts and query parameters.'],
    inputs: 'Text or a URL.',
    outputs: 'Encoded or decoded text, or a table of URL parts and query parameters.',
    example: 'hello world & more → hello%20world%20%26%20more',
    tips: ['Encode (default) escapes everything, which is right for a single query value. Tick "Keep URL characters" to encode a whole URL without breaking : / ? & #.'],
  },
  'json-converter': {
    summary: 'Convert data between JSON, CSV and YAML.',
    howTo: ['Pick a direction such as JSON → CSV.', 'Paste your data (a sample is loaded for each direction).', 'Copy the converted output.'],
    inputs: 'JSON, CSV or YAML text.',
    outputs: 'The data in the target format.',
    example: '[{"name":"Ada","age":36}] → name,age\nAda,36',
    tips: ['Nested JSON objects become dotted CSV columns like role.title.', 'CSV numbers and true/false become real JSON values.'],
  },
  'password-generator': {
    summary: 'Create strong random passwords with a strength estimate.',
    howTo: ['Set the length with the slider.', 'Tick the character types to include.', 'Click Generate and copy the password. Use Count to make several at once.'],
    inputs: 'Length and character options.',
    outputs: 'Random passwords and a strength rating in bits of entropy.',
    tips: ['Passwords are made with your browser\'s secure random generator and never leave your device.', 'Longer is stronger: 16+ characters is a good minimum.'],
  },
  'text-stats': {
    summary: 'Count words, characters, sentences and paragraphs, and generate Lorem Ipsum placeholder text.',
    howTo: ['Type or paste text to see live counts and reading time.', 'In the generator, choose paragraphs, sentences or words, and an amount.', 'Copy the placeholder text.'],
    inputs: 'Your text, or an amount of placeholder text.',
    outputs: 'Counts, reading and speaking time, and Lorem Ipsum text.',
    tips: ['Reading time assumes about 200 words per minute.'],
  },
  'finance-calculator': {
    summary: 'Work out loan payments, investment growth and returns with a set of standard finance calculators.',
    howTo: ['Pick a calculator from the tabs, e.g. Loan / Mortgage Payment or NPV.', 'Edit the numbers; results update instantly. Use Reset example to start over.', 'For cash-flow tools, type the flows separated by commas or spaces. Money you pay out is negative.', 'Copy the results, or expand the repayment schedule for loans.'],
    inputs: 'Amounts, rates in percent, years and cash flows.',
    outputs: 'The calculated figures, plus a month-by-month schedule for loans.',
    example: 'Loan 250,000 at 6.5% over 25 years → about 1,688 a month',
    tips: ['Rates are annual percentages: type 6.5 for 6.5%.', 'Included: loan, compound interest, future/present value, NPV, IRR, XIRR, ROI, payback, CAGR, Rule of 72, inflation-adjusted return, WACC and leverage ratio.', 'For information only. A lender may show slightly different figures.'],
  },
};

export const GENERAL_HELP = {
  gettingStarted: [
    'Pick a tool from the sidebar, the Home screen or the command palette (Ctrl/Cmd+K).',
    'Star tools you use often; they appear under Favorites at the top of the sidebar.',
    'Press ? (or click the ? button in the header) for help on the tool you are using.',
    'Your data stays in your browser. Tools run on your device, and nothing you type, paste or open is uploaded. The only exceptions are the desktop-app tools that exist to contact a server (DNS Lookup, Certificate Inspector, HTTP Tester, Currency Converter); they send only the request you ask for.',
  ],
  shortcuts: [
    ['Ctrl/Cmd + K', 'Open the command palette'],
    ['?  or  F1', 'Help for the current tool'],
    ['Esc', 'Close the palette or help drawer'],
  ],
};
