// Single source of truth for the sidebar, Welcome screen and App.jsx routing map.
export const CATEGORIES = ['Productivity', 'Developer Tools', 'Encoding & Security', 'Reference', 'Media'];

export const UTILITIES = [
  { id: "calculator", name: "Calculator", icon: "🧮", category: "Productivity", description: "Standard calculator with full keyboard support.", version: '1.0.0' },
  { id: "calendar", name: "Calendar", icon: "📆", category: "Productivity", description: "Month calendar with UAE weekends, public holidays, week numbers and notes.", version: '1.0.0' },
  { id: "useful-links", name: "Useful Links", icon: "🔗", category: "Productivity", description: "Manage your bookmarked URLs.", version: '1.0.0' },
  { id: "date-diff-calculator", name: "Date Difference Calculator", icon: "📅", category: "Productivity", description: "Difference between two dates in every unit.", version: '1.0.0' },
  { id: "timezone-converter", name: "Timezone Converter", icon: "🕒", category: "Productivity", description: "Convert a date/time across many timezones at once.", version: '1.0.0' },
  { id: "markdown-editor", name: "Markdown Editor", icon: "📝", category: "Productivity", description: "Side-by-side Markdown editor with live preview and export.", version: '1.0.0' },
  { id: "currency-converter", name: "Currency Converter", icon: "💱", category: "Productivity", description: "Convert between 25+ currencies with live rates.", version: '1.0.0', electronOnly: true },
  { id: "world-clock", name: "World Clock", icon: "🌍", category: "Productivity", description: "Live time in major cities on a day/night world map.", version: '1.0.0' },
  { id: "regex-tester", name: "Regex Tester", icon: "🔍", category: "Developer Tools", description: "Test regular expressions with highlighted matches and groups.", version: '1.0.0' },
  { id: "string-tools", name: "String Tools", icon: "🔤", category: "Developer Tools", description: "Case conversion, trim, reverse and text counts.", version: '1.0.0' },
  { id: "uuid-generator", name: "UUID Generator", icon: "🆔", category: "Developer Tools", description: "Generate RFC4122 v4 UUIDs in bulk.", version: '1.0.0' },
  { id: "json-viewer", name: "JSON Viewer", icon: "🌳", category: "Developer Tools", description: "Explore JSON as a collapsible, type-colored tree.", version: '1.0.0' },
  { id: "cron-parser", name: "Cron Parser", icon: "⏰", category: "Developer Tools", description: "Describe cron expressions and list upcoming runs.", version: '1.0.0' },
  { id: "yaml-comparator", name: "YAML Comparator", icon: "🔄", category: "Developer Tools", description: "Compare two YAML env configs side by side.", version: '1.0.0' },
  { id: "yaml-sorter", name: "YAML Key Sorter", icon: "🔀", category: "Developer Tools", description: "Sort YAML keys alphabetically.", version: '1.0.0' },
  { id: "code-formatter", name: "Code Formatter", icon: "✨", category: "Developer Tools", description: "Pretty-print JSON, XML, HTML, CSS and SQL.", version: '1.0.0' },
  { id: "curl-decoder", name: "cURL Decoder", icon: "🔁", category: "Developer Tools", description: "Break a curl command into readable parts.", version: '1.0.0' },
  { id: "curl-builder", name: "curl Builder", icon: "🔧", category: "Developer Tools", description: "Build a curl command from a form.", version: '1.0.0' },
  { id: "csv-viewer", name: "CSV Viewer", icon: "📋", category: "Developer Tools", description: "View CSV as a sortable, searchable table.", version: '1.0.0' },
  { id: "unix-timestamp", name: "Unix Timestamp", icon: "⏱️", category: "Developer Tools", description: "Convert between epoch and human-readable dates.", version: '1.0.0' },
  { id: "cidr-calculator", name: "IP / CIDR Calculator", icon: "🌐", category: "Developer Tools", description: "Compute network details for an IPv4 CIDR.", version: '1.0.0' },
  { id: "color-converter", name: "Color Converter", icon: "🎨", category: "Developer Tools", description: "Convert HEX/RGB/HSL/HSV with WCAG contrast analysis.", version: '1.0.0' },
  { id: "number-system-converter", name: "Number System Converter", icon: "🔢", category: "Developer Tools", description: "Convert between binary, octal, decimal, hex and custom bases.", version: '1.0.0' },
  { id: "dns-lookup", name: "DNS Lookup", icon: "🔎", category: "Developer Tools", description: "Resolve DNS records for a hostname.", version: '1.0.0', electronOnly: true },
  { id: "cert-inspector", name: "Certificate Inspector", icon: "📜", category: "Developer Tools", description: "Inspect the TLS certificate of any host:port.", version: '1.0.0', electronOnly: true },
  { id: "http-tester", name: "HTTP Request Tester", icon: "🧪", category: "Developer Tools", description: "Send HTTP requests without CORS limits.", version: '1.0.0', electronOnly: true },
  { id: "http-mock-server", name: "HTTP Mock Server", icon: "🎭", category: "Developer Tools", description: "Run a local mock server with stub routes and a live log.", version: '1.0.0', electronOnly: true },
  { id: "fake-data-generator", name: "Fake Data Generator", icon: "🧑‍🤝‍🧑", category: "Developer Tools", description: "Generate realistic offline test data as JSON or CSV.", version: '1.0.0' },
  { id: "base64", name: "Base64 Tool", icon: "🔐", category: "Encoding & Security", description: "Encode and decode Base64 text.", version: '1.0.0' },
  { id: "hash-generator", name: "Hash Generator", icon: "#️⃣", category: "Encoding & Security", description: "Generate MD5, SHA-1, SHA-256 and SHA-512 hashes.", version: '1.0.0' },
  { id: "jwt-decoder", name: "JWT Decoder", icon: "🔓", category: "Encoding & Security", description: "Decode JWT header and payload and check expiry.", version: '1.0.0' },
  { id: "card-validator", name: "Card / IBAN Validator", icon: "💳", category: "Encoding & Security", description: "Validate card numbers (Luhn) and IBANs (MOD-97) offline.", version: '1.0.0' },
  { id: "cheatsheet", name: "Cheatsheet", icon: "📚", category: "Reference", description: "Searchable command reference for Git, Docker, Linux and more.", version: '1.0.0' },
  { id: "image-tools", name: "Image Tools", icon: "🖼️", category: "Media", description: "Convert, compress and export images to PDF.", version: '1.0.0' },
  { id: "qr-code-generator", name: "QR Code Generator", icon: "🔳", category: "Media", description: "Generate QR codes for URLs, text and Wi-Fi.", version: '1.0.0' },
  { id: "text-diff", name: "Text Diff", icon: "↔️", category: "Developer Tools", description: "Compare two texts line by line and see what changed.", version: '1.0.0' },
  { id: "url-tools", name: "URL Encode / Decode", icon: "🔗", category: "Developer Tools", description: "Percent-encode, decode and break a URL into its parts.", version: '1.0.0' },
  { id: "json-converter", name: "JSON Converter", icon: "🔁", category: "Developer Tools", description: "Convert between JSON, CSV and YAML.", version: '1.0.0' },
  { id: "password-generator", name: "Password Generator", icon: "🔑", category: "Encoding & Security", description: "Generate strong random passwords with a strength meter.", version: '1.0.0' },
  { id: "text-stats", name: "Word Counter & Lorem Ipsum", icon: "🔢", category: "Productivity", description: "Count words and characters, and generate placeholder text.", version: '1.0.0' },
];
